# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

meansd <- function(x) {
    .Call('_ckmisc_meansd', PACKAGE = 'ckmisc', x)
}

fquantile <- function(x, probs, na_rm = TRUE) {
    .Call('_ckmisc_fquantile', PACKAGE = 'ckmisc', x, probs, na_rm)
}

fquantile_byid <- function(x, q, id) {
    .Call('_ckmisc_fquantile_byid', PACKAGE = 'ckmisc', x, q, id)
}

QDriskDF <- function(df, surv) {
    .Call('_ckmisc_QDriskDF', PACKAGE = 'ckmisc', df, surv)
}

QDrisk <- function(age, sex, b_corticosteroids, b_treatedhyp, bmi, ethrisk, fh_diab, smoke_cat, town, surv) {
    .Call('_ckmisc_QDrisk', PACKAGE = 'ckmisc', age, sex, b_corticosteroids, b_treatedhyp, bmi, ethrisk, fh_diab, smoke_cat, town, surv)
}

cvd_raw <- function(age, sex, b_AF, b_ra, b_renal, b_treatedhyp, b_type1, b_type2, bmi, ethrisk, fh_cvd, rati, sbp, smoke_cat, town) {
    .Call('_ckmisc_cvd_raw', PACKAGE = 'ckmisc', age, sex, b_AF, b_ra, b_renal, b_treatedhyp, b_type1, b_type2, bmi, ethrisk, fh_cvd, rati, sbp, smoke_cat, town)
}

QRisk <- function(age, sex, b_AF, b_ra, b_renal, b_treatedhyp, b_type1, b_type2, bmi, ethrisk, fh_cvd, rati, sbp, smoke_cat, town) {
    .Call('_ckmisc_QRisk', PACKAGE = 'ckmisc', age, sex, b_AF, b_ra, b_renal, b_treatedhyp, b_type1, b_type2, bmi, ethrisk, fh_cvd, rati, sbp, smoke_cat, town)
}

fbound <- function(x, a, b) {
    .Call('_ckmisc_fbound', PACKAGE = 'ckmisc', x, a, b)
}

fbound_inplace <- function(x, a, b) {
    .Call('_ckmisc_fbound_inplace', PACKAGE = 'ckmisc', x, a, b)
}

fbound_inplace_int <- function(x, a, b) {
    .Call('_ckmisc_fbound_inplace_int', PACKAGE = 'ckmisc', x, a, b)
}

fequal <- function(x, tol) {
    .Call('_ckmisc_fequal', PACKAGE = 'ckmisc', x, tol)
}

fnormalise <- function(x) {
    .Call('_ckmisc_fnormalise', PACKAGE = 'ckmisc', x)
}

fcompress <- function(x, limit) {
    .Call('_ckmisc_fcompress', PACKAGE = 'ckmisc', x, limit)
}

count_if <- function(x) {
    .Call('_ckmisc_count_if', PACKAGE = 'ckmisc', x)
}

prop_if <- function(x, na_rm = TRUE) {
    .Call('_ckmisc_prop_if', PACKAGE = 'ckmisc', x, na_rm)
}

df2mat_numeric <- function(x) {
    .Call('_ckmisc_df2mat_numeric', PACKAGE = 'ckmisc', x)
}

df2mat_integer <- function(x) {
    .Call('_ckmisc_df2mat_integer', PACKAGE = 'ckmisc', x)
}

tableRcpp <- function(x) {
    .Call('_ckmisc_tableRcpp', PACKAGE = 'ckmisc', x)
}

counts <- function(x) {
    .Call('_ckmisc_counts', PACKAGE = 'ckmisc', x)
}

counts_DF <- function(x) {
    .Call('_ckmisc_counts_DF', PACKAGE = 'ckmisc', x)
}

roll_mean <- function(dat, window) {
    .Call('_ckmisc_roll_mean', PACKAGE = 'ckmisc', dat, window)
}

simsmokDF <- function(df, pr_relap, relap_cutoff) {
    .Call('_ckmisc_simsmokDF', PACKAGE = 'ckmisc', df, pr_relap, relap_cutoff)
}

simsmok <- function(cigst1, pr_init, pr_cess, dice, id, age, sex, qimd, endsmoke, smokyrs, cigdyal, numsmok, year, cigdyal_rank, pr_relap, relap_cutoff) {
    .Call('_ckmisc_simsmok', PACKAGE = 'ckmisc', cigst1, pr_init, pr_cess, dice, id, age, sex, qimd, endsmoke, smokyrs, cigdyal, numsmok, year, cigdyal_rank, pr_relap, relap_cutoff)
}

numsmok_fix <- function(cigst1, id, cigdyal, numsmok) {
    .Call('_ckmisc_numsmok_fix', PACKAGE = 'ckmisc', cigst1, id, cigdyal, numsmok)
}

shift_byidNum <- function(x, lag, replace, id) {
    .Call('_ckmisc_shift_byidNum', PACKAGE = 'ckmisc', x, lag, replace, id)
}

shift_byidInt <- function(x, lag, replace, id) {
    .Call('_ckmisc_shift_byidInt', PACKAGE = 'ckmisc', x, lag, replace, id)
}

shift_byidStr <- function(x, lag, replace, id) {
    .Call('_ckmisc_shift_byidStr', PACKAGE = 'ckmisc', x, lag, replace, id)
}

incidence_events <- function(diab, pr_diab_cvd, pr_diab_nocvd, dice_diab_inc, chd, pr_chd_inc, chd_diab_rr, dice_chd_inc, stroke, pr_stroke_inc, stroke_diab_rr, dice_stroke_inc, id, year, lag) {
    .Call('_ckmisc_incidence_events', PACKAGE = 'ckmisc', diab, pr_diab_cvd, pr_diab_nocvd, dice_diab_inc, chd, pr_chd_inc, chd_diab_rr, dice_chd_inc, stroke, pr_stroke_inc, stroke_diab_rr, dice_stroke_inc, id, year, lag)
}

mortality_events <- function(px_disease, px_disease_dice, id, code) {
    .Call('_ckmisc_mortality_events', PACKAGE = 'ckmisc', px_disease, px_disease_dice, id, code)
}

collect_output <- function(x1, x2, x3, x4, x5, x6, x7, a0, a1, a2, a3, a4) {
    .Call('_ckmisc_collect_output', PACKAGE = 'ckmisc', x1, x2, x3, x4, x5, x6, x7, a0, a1, a2, a3, a4)
}

HC_coverage <- function(id, coverage, dice) {
    .Call('_ckmisc_HC_coverage', PACKAGE = 'ckmisc', id, coverage, dice)
}

HC_effect <- function(id, participated, invited) {
    .Call('_ckmisc_HC_effect', PACKAGE = 'ckmisc', id, participated, invited)
}

med_effect <- function(id, med_taken, participation_effect) {
    .Call('_ckmisc_med_effect', PACKAGE = 'ckmisc', id, med_taken, participation_effect)
}

bariatricsurg_effect <- function(id, bmi, behav_effect, participated) {
    .Call('_ckmisc_bariatricsurg_effect', PACKAGE = 'ckmisc', id, bmi, behav_effect, participated)
}

smokclinic_effect <- function(id, cigst1, behav_effect, participated) {
    .Call('_ckmisc_smokclinic_effect', PACKAGE = 'ckmisc', id, cigst1, behav_effect, participated)
}

predict_svylr <- function(x, e, y, z, rank) {
    .Call('_ckmisc_predict_svylr', PACKAGE = 'ckmisc', x, e, y, z, rank)
}

